export  const FETCH_MEAL_BID_INPUT_SUCCESS = 'FETCH_MEAL_BID_INPUT_SUCCESS';
export  const ERROR_OCCURED = 'ERROR_OCCURED';
export  const SELECT_JOURNEY_SUCCESS = 'SELECT_JOURNEY_SUCCESS';
export  const BACK_JOURNEY_PAGE_SUCCESS = 'BACK_JOURNEY_PAGE_SUCCESS';
export  const JOURNEY_MEALS_SELECTION_SUCCESS = 'JOURNEY_MEALS_SELECTION_SUCCESS';
export  const ALL_JOURNEY_MEALS_NOT_COMPLETE = 'ALL_JOURNEY_MEALS_NOT_COMPLETE';
export  const CURRENT_JOURNEY_MEALS_NOT_COMPLETE = 'CURRENT_JOURNEY_MEALS_NOT_COMPLETE';
export  const RESET_ERROR = 'RESET_ERROR';
